/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Start */
        get: operations["google_start_api_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Wishlist */
        post: operations["create_wishlist_api_v1_wishlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Wishlists */
        get: operations["list_my_wishlists_api_v1_wishlists_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wishlist */
        get: operations["get_wishlist_api_v1_wishlists__wishlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Wishlist */
        patch: operations["update_wishlist_api_v1_wishlists__wishlist_id__patch"];
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Wishlist */
        post: operations["publish_wishlist_api_v1_wishlists__wishlist_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Wishlist */
        post: operations["close_wishlist_api_v1_wishlists__wishlist_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_wishlists__wishlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_wishlists__wishlist_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/items/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Item */
        post: operations["archive_item_api_v1_wishlists__wishlist_id__items__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/items/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Items */
        post: operations["reorder_items_api_v1_wishlists__wishlist_id__items_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlists/{wishlist_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats Placeholder */
        get: operations["stats_placeholder_api_v1_wishlists__wishlist_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/w/{share_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Wishlist */
        get: operations["get_public_wishlist_api_v1_public_w__share_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/w/{share_slug}/guest-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Guest Session */
        post: operations["create_guest_session_api_v1_public_w__share_slug__guest_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/w/{share_slug}/items/{item_id}/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve Item */
        post: operations["reserve_item_api_v1_public_w__share_slug__items__item_id__reserve_post"];
        /** Unreserve Item */
        delete: operations["unreserve_item_api_v1_public_w__share_slug__items__item_id__reserve_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/w/{share_slug}/items/{item_id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contribute To Item */
        post: operations["contribute_to_item_api_v1_public_w__share_slug__items__item_id__contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/w/{share_slug}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_public_w__share_slug__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Item */
        post: operations["preview_item_api_v1_items_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["AuthUser"];
        };
        /** AuthUser */
        AuthUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ContributionRequest */
        ContributionRequest: {
            /** Amount */
            amount: number | string;
        };
        /** ContributionResponse */
        ContributionResponse: {
            /** Message */
            message: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Accepted Amount */
            accepted_amount: string;
            /** Collected Amount */
            collected_amount: string;
            /** Progress Percent */
            progress_percent: number;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "item_reserved" | "item_unreserved" | "contribution_added" | "item_updated" | "item_archived" | "wishlist_published" | "wishlist_closed";
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["RealtimeEventView"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** GuestItemView */
        GuestItemView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Product Url */
            product_url: string | null;
            /** Image Url */
            image_url: string | null;
            /** Notes */
            notes: string | null;
            /** Price */
            price: string | null;
            mode: components["schemas"]["ItemMode"];
            /** Target Amount */
            target_amount: string | null;
            /** Collected Amount */
            collected_amount: string;
            status: components["schemas"]["ItemStatus"];
            /** Position */
            position: number;
            /** Is Reserved */
            is_reserved: boolean;
            /** Reserved By You */
            reserved_by_you: boolean;
            /** My Contribution */
            my_contribution: string;
            /** Progress Percent */
            progress_percent: number;
        };
        /** GuestSessionCreateRequest */
        GuestSessionCreateRequest: {
            /** Name */
            name: string;
        };
        /** GuestSessionResponse */
        GuestSessionResponse: {
            /** Token */
            token: string;
            /**
             * Guest Session Id
             * Format: uuid
             */
            guest_session_id: string;
            /** Guest Name */
            guest_name: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemMode
         * @enum {string}
         */
        ItemMode: "single" | "group";
        /** ItemPreviewRequest */
        ItemPreviewRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ItemPreviewResponse */
        ItemPreviewResponse: {
            /** Title */
            title: string | null;
            /** Image Url */
            image_url: string | null;
            /** Price */
            price: string | null;
            /** Currency */
            currency: string | null;
            /** Source Url */
            source_url: string;
            /** From Cache */
            from_cache: boolean;
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "active" | "archived" | "unavailable";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** OwnerItemView */
        OwnerItemView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Product Url */
            product_url: string | null;
            /** Image Url */
            image_url: string | null;
            /** Notes */
            notes: string | null;
            /** Price */
            price: string | null;
            mode: components["schemas"]["ItemMode"];
            /** Target Amount */
            target_amount: string | null;
            /** Collected Amount */
            collected_amount: string;
            status: components["schemas"]["ItemStatus"];
            /** Position */
            position: number;
            /** Is Reserved */
            is_reserved: boolean;
            /** Progress Percent */
            progress_percent: number;
        };
        /** OwnerWishlistDetail */
        OwnerWishlistDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Occasion */
            occasion: string | null;
            /** Currency */
            currency: string;
            /** Event Date */
            event_date: string | null;
            status: components["schemas"]["WishlistStatus"];
            /** Share Slug */
            share_slug: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Items */
            items: components["schemas"]["OwnerItemView"][];
        };
        /** PublicWishlistView */
        PublicWishlistView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Occasion */
            occasion: string | null;
            /** Currency */
            currency: string;
            /** Event Date */
            event_date: string | null;
            status: components["schemas"]["WishlistStatus"];
            /** Share Slug */
            share_slug: string;
            /**
             * Viewer Kind
             * @enum {string}
             */
            viewer_kind: "anonymous" | "guest" | "owner";
            /** Items */
            items: components["schemas"]["GuestItemView"][] | components["schemas"]["OwnerItemView"][];
        };
        /** RealtimeEventView */
        RealtimeEventView: {
            /** Id */
            id: number;
            event_type: components["schemas"]["EventType"];
            /** Item Id */
            item_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** ReservationResponse */
        ReservationResponse: {
            /** Message */
            message: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Is Reserved */
            is_reserved: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WishlistCreateRequest */
        WishlistCreateRequest: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Occasion */
            occasion?: string | null;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /** Event Date */
            event_date?: string | null;
        };
        /** WishlistItemCreateRequest */
        WishlistItemCreateRequest: {
            /** Title */
            title: string;
            /** Product Url */
            product_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Price */
            price?: number | string | null;
            /** @default single */
            mode: components["schemas"]["ItemMode"];
            /** Target Amount */
            target_amount?: number | string | null;
            /** Position */
            position?: number | null;
        };
        /** WishlistItemReorderRequest */
        WishlistItemReorderRequest: {
            /** Item Ids */
            item_ids: string[];
        };
        /** WishlistItemUpdateRequest */
        WishlistItemUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Product Url */
            product_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Price */
            price?: number | string | null;
            mode?: components["schemas"]["ItemMode"] | null;
            /** Target Amount */
            target_amount?: number | string | null;
            status?: components["schemas"]["ItemStatus"] | null;
        };
        /**
         * WishlistStatus
         * @enum {string}
         */
        WishlistStatus: "draft" | "published" | "closed";
        /** WishlistSummary */
        WishlistSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Occasion */
            occasion: string | null;
            /** Currency */
            currency: string;
            /** Event Date */
            event_date: string | null;
            status: components["schemas"]["WishlistStatus"];
            /** Share Slug */
            share_slug: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WishlistUpdateRequest */
        WishlistUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Occasion */
            occasion?: string | null;
            /** Currency */
            currency?: string | null;
            /** Event Date */
            event_date?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wishlist_refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_start_api_v1_auth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_wishlist_api_v1_wishlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_wishlists_api_v1_wishlists_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wishlist_api_v1_wishlists__wishlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wishlist_api_v1_wishlists__wishlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_wishlist_api_v1_wishlists__wishlist_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_wishlist_api_v1_wishlists__wishlist_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_wishlists__wishlist_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_wishlists__wishlist_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
                item_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistItemUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_item_api_v1_wishlists__wishlist_id__items__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
                item_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_items_api_v1_wishlists__wishlist_id__items_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistItemReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWishlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_placeholder_api_v1_wishlists__wishlist_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_wishlist_api_v1_public_w__share_slug__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Guest-Token"?: string | null;
            };
            path: {
                share_slug: string;
            };
            cookie?: {
                wishlist_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicWishlistView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_guest_session_api_v1_public_w__share_slug__guest_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reserve_item_api_v1_public_w__share_slug__items__item_id__reserve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Guest-Token"?: string | null;
            };
            path: {
                share_slug: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unreserve_item_api_v1_public_w__share_slug__items__item_id__reserve_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Guest-Token"?: string | null;
            };
            path: {
                share_slug: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contribute_to_item_api_v1_public_w__share_slug__items__item_id__contributions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Guest-Token"?: string | null;
            };
            path: {
                share_slug: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_v1_public_w__share_slug__events_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                share_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_item_api_v1_items_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
